/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "http_pusher.h"
/* Header for class org_easydarwin_push_HttpPusher */

#ifndef _Included_org_easydarwin_push_HttpPusher
#define _Included_org_easydarwin_push_HttpPusher
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_easydarwin_push_HttpPusher
 * Method:    connect
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_coship_live_rtmp_jni_RtmpJni_connectTsServer
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_easydarwin_push_HttpPusher
 * Method:    push
 * Signature: ([BJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_easydarwin_push_HttpPusher_push
  (JNIEnv *, jobject, jbyteArray, jlong, jstring);

/*
 * Class:     org_easydarwin_push_HttpPusher
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_coship_live_rtmp_jni_RtmpJni_closeTs
  (JNIEnv *, jobject);

JNIEXPORT jint JNICALL Java_com_coship_live_rtmp_jni_RtmpJni_pushDataMux
        (JNIEnv *, jobject, jbyteArray, jlong,jint);

JNIEXPORT jint JNICALL Java_com_coship_live_rtmp_jni_RtmpJni_httpStatus(JNIEnv *, jobject);



#ifdef __cplusplus
}
#endif
#endif
